version: "3.9"

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - weather

  metermaid:
    build: ./metermaid/
    restart: always
    ports:
      - 1234:1234
    volumes:
      - ./meter_data:/data
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - weather

  weatherscript:
    build: ./weather/
    restart: always
    volumes:
      - ./weather_data:/data
    networks:
      - weather

volumes:
  grafana-storage:

networks:
  weather:
