version: "3.9"

services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - weather

  metermaid:
    build: ./metermaid/
    restart: always
    volumes:
      - ./meter_data:/data
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - weather

  weatherscript:
    build: ./weather/
    restart: always
    volumes:
      - ./weather_data:/data
    environment:
      - LOCATION=YOUR_LOCATION
      - API_KEY=YOUR_API_KEY
    networks:
      - weather

volumes:
  grafana-storage:

networks:
  weather:
